version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    ports:
      - "3306:3306"  # 호스트와 컨테이너의 포트 매핑
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4!!  # 루트 계정 비밀번호
      MYSQL_DATABASE: onion-db         # 생성할 기본 데이터베이스 이름
      MYSQL_USER: matthew              # 사용자 이름
      MYSQL_PASSWORD: q1w2e3r4!!       # 사용자 비밀번호

    volumes:
      - db_data:/var/lib/mysql       # 데이터 영구 저장소 설정


volumes:
  db_data:
